### ISSUE TITLE
IAM roles with paths are only recognized without the path

### ISSUE THREAD

**Issue by devkid** [kubernetes-sigs/aws-iam-authenticator#153]
Assuming I have the following role ARN:

```
arn:aws:iam::1234567890:role/iam-ss/some-path/actual-role-name
```

If I enter this under `mapRoles`, this will not be recognized. Instead I need to enter:

```
arn:aws:iam::1234567890:role/actual-role-name
```

**Comment by davekonopka** [comment]
@devkid Are you using an assumed role? It looks like this PR might be related to what you're seeing: https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/144

**Comment by devkid** [comment]
The role is used by an EC2 instance with an IAM instance profile. Not sure if this counts as "assumed"? (Does EC2 "assume" the role on behalf of the instance to provide the credentials?)

**Comment by davekonopka** [comment]
Yes. Roles are always assumed now that I think about it.

**Comment by timvanderkooi** [comment]
Any update here? I'd like to be able to use Terraform to resolve the ARN and place it into my auth map, but with this implementation I have to manually specify that modified ARN as a variable.

**Comment by fgoncalves-io** [comment]
@timvanderkooi, good news! Apparently this was solved by #103 and it's already part of the pre-release v0.4.0-alpha.1.

**Comment by jpb** [comment]
I ran into this, and the fix in #103 isn't sufficient to resolve the issue because role paths are not included in `assumed-role` ARNs. I created #144 which implements @nckturner's option (1.) or (2.) (not sure which one based on the description above), but it is currently stalled right now.

Given that roles are unique based on their name only, it would be safe to drop the path in the role ARN in `mapRoles` as a temporary workaround.

**Comment by jeremwa** [comment]
Still seeing the appearance off this issue. in configMap having to drop path:
`- rolearn: arn:aws:iam::1234567890:role/prod-path/eks-role`
in automation needs to be parsed down to 
`- rolearn: arn:aws:iam::12334567890:role/eks-role`

Following EKS Setup documentation, this can initially manifest in Nodes not being able to join the cluster after the instance role is passed to the auth config step.

**Comment by jalvarezferr** [comment]
Using AWS EKS with a worker role having an IAM path other than / causes worker to fail to join the cluster.
/var/log/messages shows streams of Unauthorized errors.
Is this related to this same issue?

**Comment by devkid** [comment]
@jalvarezferr Yes, that is the issue. Just cut out the path, it should work then.

**Comment by zettatronn** [comment]
/reopen 

This ticket was closed due to inactivity but this bug is still present. We currently have to use 2 ARNs in all configmaps to work around this issue.

**Comment by billinghamj** [comment]
Between #333, #268, #153 and #98 - would be good to get duplicates closed and it tracked in one place

**Comment by sftim** [comment]
If people want to highlight this issue to the vendor, AWS, then please visit https://github.com/aws/containers-roadmap/issues/573 and add a thumbs-up reaction.

**Comment by gothrek22** [comment]
Seems that it's kind of fixed upstream here: https://github.com/aws/containers-roadmap/issues/185

They now not only support an API to manage cluster access, but also switch to AWS iam principal id, instead of ARN (which is relevant to this ticket).
