### ISSUE TITLE
Add support for `external_id` when assuming a role

### ISSUE THREAD

**Issue by benderillo** [kubernetes-sigs/aws-iam-authenticator#209]
At the moment there is no way to specify `external_id` when specifying a role.
This makes it impossible to use `aws-ima-authenticator` to assume role that has `sts:ExternalId` condition set.

Here is our use case:
Terraform is used to bring up EKS cluster. Terraform assumes a role that has `sts:ExternalId` condition set. Terraform allows to specify `external_id` so there is no issue here.

However, the last step in setting up an EKS cluster and adding worker nodes to it implies that we need to `kubectl apply` a ConfigMap with Auth settings to allow worker nodes to join the cluster.

Before we can do `kubectl apply` we need to configure `kubectl` to access the cluster.
To do so, we need to use `aws-iam-authenticator token` with `-r role-arn` argument. 

The problem is, it will not work because there is no way to tell `aws-iam-authenticator token` to use `external_id` to get an access.

So we stuck not being able to complete the cluster setup.
I have submitted another request for aws-cli to add support for `external_id` parameter when running `aws eks update-kubeconfig`: https://github.com/aws/aws-cli/issues/4053

**Comment by bensussman** [comment]
This is a major blocker for us, as we need the `external_id` to protect us from the confused deputy problem, but we are open to this attack for all of our external EKS clusters because there is no `external_id` support.

Please help @nckturner!

**Comment by nckturner** [comment]
After a quick glance at the code it looks like it would need to be passed down and set on `sessionSetter` here: https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/master/pkg/token/token.go#L243

The aws-cli issue that you linked states that a change would need to be made to the server side as well, but I'm not sure I understand that yet--my understanding is that the externalID would be used by the client when the role is assumed, and once the credentials come back, then the externalID has been verified in the trust policy of the role and we can forget about it.  Am I missing something here?

**Comment by benderillo** [comment]
@nckturner I have the same understanding and also not quite sure why the `server` was mentioned.
Maybe @justnance can elaborate on that comment?

**Comment by bensussman** [comment]
@nckturner The issue that is clear to me is that `aws-iam-authenticator` cannot accept `external_id` when the `-r <role_arn>` argument is provided. I am able to reproduce by running:

```
aws-iam-authenticator token -i <my-eks-cluster> -r <role-that-has-cluster-perms>
```

This command above work work fine if `role-that-has-cluster-perms` does NOT have an external ID. If i go into the AWS IAM console and add an external ID to that role, the cmd above will cease to work.

You can read about external IDs here: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user_externalid.html

I assume the fix is purely client side, I have personally used something that looks like this:

```
import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/aws/external"
	"github.com/aws/aws-sdk-go-v2/aws/stscreds"
	"github.com/aws/aws-sdk-go-v2/service/sts"
)

func GetExternalRoleCredentialsProvider(roleARN string, externalID string) (aws.CredentialsProvider, errors.E) {
	cfg, err := external.LoadDefaultAWSConfig()
	if err != nil {
		return nil, errors.Wrapf(err, "Unable to load aws config")
	}
	stsCli := sts.New(cfg)
	ar := AssumeRoler{
		stsCli:     stsCli,
		externalID: externalID,
	}
	return stscreds.NewAssumeRoleProvider(ar, roleARN), nil
}
```

Ultimately what needs to be added is that the `-r` flag should have an accompanying `--external-id` flag (or something similar) that allows users to pass in an external id to protect against a Confused Deputy attack.

**Comment by bensussman** [comment]
@nckturner any update on this?

**Comment by nckturner** [comment]
No, I haven't had a chance to take this on, but if someone wants to give it a try I'd be happy to review.  
/cc @micahhausler

**Comment by bensussman** [comment]
Pretty sure this issue is not rotten/stale but fully fixed with https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/228 and can be closed?

**Comment by mailjunze** [comment]
aws-iam-authenticator still doesn't support this feature
aws-iam-authenticator token [flags]Flags:
      --cache                  Cache the credential on disk until it expires. Uses the aws profile specified by AWS_PROFILE or the default profile.
      --forward-session-name   Enable mapping a federated sessions caller-specified-role-name attribute onto newly assumed sessions. NOTE: Only applicable when a new role is requested via --role
  -h, --help                   help for token
  -r, --role string            Assume an IAM Role ARN before signing this token
      --token-only             Return only the token for use with Bearer token based tools
